import type { RickAndMortyCharacter } from '@/shared';

export const MOCK_CHARACTERS_DATA: RickAndMortyCharacter[] = [
  {
    created: '2017-11-04T18:48:46.250Z',
    gender: 'Male',
    id: 1,
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    location: 'Citadel of Ricks',
    name: 'Rick Sanchez',
    origin: 'Earth (C-137)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T18:50:21.651Z',
    gender: 'Male',
    id: 2,
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    location: 'Citadel of Ricks',
    name: 'Morty Smith',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:09:56.428Z',
    gender: 'Female',
    id: 3,
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Summer Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:22:43.665Z',
    gender: 'Female',
    id: 4,
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Beth Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:26:56.301Z',
    gender: 'Male',
    id: 5,
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Jerry Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:50:28.250Z',
    gender: 'Female',
    id: 6,
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    location: 'Abadango',
    name: 'Abadango Cluster Princess',
    origin: 'Abadango',
    species: 'Alien',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:59:20.523Z',
    gender: 'Male',
    id: 7,
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    location: 'Testicle Monster Dimension',
    name: 'Abradolf Lincler',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'unknown',
    type: 'Genetic experiment',
  },
  {
    created: '2017-11-04T20:03:34.737Z',
    gender: 'Male',
    id: 8,
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    location: 'Citadel of Ricks',
    name: 'Adjudicator Rick',
    origin: 'unknown',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:06:54.976Z',
    gender: 'Male',
    id: 9,
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Agency Director',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:19:09.017Z',
    gender: 'Male',
    id: 10,
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    location: "Worldender's lair",
    name: 'Alan Rails',
    origin: 'unknown',
    species: 'Human',
    status: 'Dead',
    type: 'Superhuman (Ghost trains summoner)',
  },
  {
    created: '2017-11-04T20:20:20.965Z',
    gender: 'Male',
    id: 11,
    image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Albert Einstein',
    origin: 'Earth (C-137)',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:32:33.144Z',
    gender: 'Male',
    id: 12,
    image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
    location: 'Anatomy Park',
    name: 'Alexander',
    origin: 'Earth (C-137)',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:33:30.779Z',
    gender: 'unknown',
    id: 13,
    image: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Alien Googah',
    origin: 'unknown',
    species: 'Alien',
    status: 'unknown',
    type: '',
  },
  {
    created: '2017-11-04T20:51:31.373Z',
    gender: 'Male',
    id: 14,
    image: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
    location: 'Citadel of Ricks',
    name: 'Alien Morty',
    origin: 'unknown',
    species: 'Alien',
    status: 'unknown',
    type: '',
  },
  {
    created: '2017-11-04T20:56:13.215Z',
    gender: 'Male',
    id: 15,
    image: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
    location: 'Citadel of Ricks',
    name: 'Alien Rick',
    origin: 'unknown',
    species: 'Alien',
    status: 'unknown',
    type: '',
  },
  {
    created: '2017-11-04T21:12:45.235Z',
    gender: 'Male',
    id: 16,
    image: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Amish Cyborg',
    origin: 'unknown',
    species: 'Alien',
    status: 'Dead',
    type: 'Parasite',
  },
  {
    created: '2017-11-04T22:21:24.481Z',
    gender: 'Female',
    id: 17,
    image: 'https://rickandmortyapi.com/api/character/avatar/17.jpeg',
    location: 'Anatomy Park',
    name: 'Annie',
    origin: 'Earth (C-137)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T22:25:29.008Z',
    gender: 'Male',
    id: 18,
    image: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
    location: 'Citadel of Ricks',
    name: 'Antenna Morty',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: 'Human with antennae',
  },
  {
    created: '2017-11-04T22:28:13.756Z',
    gender: 'Male',
    id: 19,
    image: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
    location: 'unknown',
    name: 'Antenna Rick',
    origin: 'unknown',
    species: 'Human',
    status: 'unknown',
    type: 'Human with antennae',
  },
  {
    created: '2017-11-04T22:34:53.659Z',
    gender: 'Male',
    id: 20,
    image: 'https://rickandmortyapi.com/api/character/avatar/20.jpeg',
    location: 'Interdimensional Cable',
    name: 'Ants in my Eyes Johnson',
    origin: 'unknown',
    species: 'Human',
    status: 'unknown',
    type: 'Human with ants in his eyes',
  },
  {
    created: '2017-11-04T22:39:48.055Z',
    gender: 'Male',
    id: 21,
    image: 'https://rickandmortyapi.com/api/character/avatar/21.jpeg',
    location: 'Citadel of Ricks',
    name: 'Aqua Morty',
    origin: 'unknown',
    species: 'Humanoid',
    status: 'unknown',
    type: 'Fish-Person',
  },
  {
    created: '2017-11-04T22:41:07.171Z',
    gender: 'Male',
    id: 22,
    image: 'https://rickandmortyapi.com/api/character/avatar/22.jpeg',
    location: 'Citadel of Ricks',
    name: 'Aqua Rick',
    origin: 'unknown',
    species: 'Humanoid',
    status: 'unknown',
    type: 'Fish-Person',
  },
  {
    created: '2017-11-05T08:43:05.095Z',
    gender: 'Male',
    id: 23,
    image: 'https://rickandmortyapi.com/api/character/avatar/23.jpeg',
    location: 'Immortality Field Resort',
    name: 'Arcade Alien',
    origin: 'unknown',
    species: 'Alien',
    status: 'unknown',
    type: '',
  },
  {
    created: '2017-11-05T08:48:30.776Z',
    gender: 'Male',
    id: 24,
    image: 'https://rickandmortyapi.com/api/character/avatar/24.jpeg',
    location: 'Signus 5 Expanse',
    name: 'Armagheadon',
    origin: 'Signus 5 Expanse',
    species: 'Alien',
    status: 'Alive',
    type: 'Cromulon',
  },
  {
    created: '2017-11-05T08:54:29.343Z',
    gender: 'Male',
    id: 25,
    image: 'https://rickandmortyapi.com/api/character/avatar/25.jpeg',
    location: 'Post-Apocalyptic Earth',
    name: 'Armothy',
    origin: 'Post-Apocalyptic Earth',
    species: 'unknown',
    status: 'Dead',
    type: 'Self-aware arm',
  },
  {
    created: '2017-11-05T08:56:46.165Z',
    gender: 'Female',
    id: 26,
    image: 'https://rickandmortyapi.com/api/character/avatar/26.jpeg',
    location: 'Purge Planet',
    name: 'Arthricia',
    origin: 'Purge Planet',
    species: 'Alien',
    status: 'Alive',
    type: 'Cat-Person',
  },
  {
    created: '2017-11-05T08:59:07.457Z',
    gender: 'Male',
    id: 27,
    image: 'https://rickandmortyapi.com/api/character/avatar/27.jpeg',
    location: 'Citadel of Ricks',
    name: 'Artist Morty',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-05T09:02:16.595Z',
    gender: 'Male',
    id: 28,
    image: 'https://rickandmortyapi.com/api/character/avatar/28.jpeg',
    location: 'Interdimensional Cable',
    name: 'Attila Starwar',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-05T09:06:19.644Z',
    gender: 'Male',
    id: 29,
    image: 'https://rickandmortyapi.com/api/character/avatar/29.jpeg',
    location: 'Interdimensional Cable',
    name: 'Baby Legs',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: 'Human with baby legs',
  },
  {
    created: '2017-11-05T09:13:16.483Z',
    gender: 'Male',
    id: 30,
    image: 'https://rickandmortyapi.com/api/character/avatar/30.jpeg',
    location: 'unknown',
    name: 'Baby Poopybutthole',
    origin: 'unknown',
    species: 'Poopybutthole',
    status: 'Alive',
    type: '',
  },
];
