import type { RickAndMortyCharacter } from '@/shared';

export const MOCK_CHARACTERS_DATA: RickAndMortyCharacter[] = [
  {
    created: '2017-11-04T18:48:46.250Z',
    gender: 'Male',
    id: 1,
    image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    location: 'Citadel of Ricks',
    name: 'Rick Sanchez',
    origin: 'Earth (C-137)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T18:50:21.651Z',
    gender: 'Male',
    id: 2,
    image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    location: 'Citadel of Ricks',
    name: 'Morty Smith',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:09:56.428Z',
    gender: 'Female',
    id: 3,
    image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Summer Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:22:43.665Z',
    gender: 'Female',
    id: 4,
    image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Beth Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:26:56.301Z',
    gender: 'Male',
    id: 5,
    image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Jerry Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:50:28.250Z',
    gender: 'Female',
    id: 6,
    image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    location: 'Abadango',
    name: 'Abadango Cluster Princess',
    origin: 'Abadango',
    species: 'Alien',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:59:20.523Z',
    gender: 'Male',
    id: 7,
    image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    location: 'Testicle Monster Dimension',
    name: 'Abradolf Lincler',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'unknown',
    type: 'Genetic experiment',
  },
  {
    created: '2017-11-04T20:03:34.737Z',
    gender: 'Male',
    id: 8,
    image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
    location: 'Citadel of Ricks',
    name: 'Adjudicator Rick',
    origin: 'unknown',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:06:54.976Z',
    gender: 'Male',
    id: 9,
    image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    location: 'Earth (Replacement Dimension)',
    name: 'Agency Director',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:19:09.017Z',
    gender: 'Male',
    id: 10,
    image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
    location: "Worldender's lair",
    name: 'Alan Rails',
    origin: 'unknown',
    species: 'Human',
    status: 'Dead',
    type: 'Superhuman (Ghost trains summoner)',
  },
];
