import type { RickAndMortyCharacter } from './types';

export const CACHE_KEY = {
  searchQuery: 'RAM_SearchQuery',
};

export const PAGE_SIZE = 10;

export const ERROR_MESSAGES = {
  FAILED_TO_FETCH_DATA: 'Failed to fetch data:',
  HTTP_ERROR: 'HTTP error! Status: ',
  NO_RESULTS_FOUND: 'No results found for your search for ',
  NOT_FOUND: 'The page you are looking for does not exist.',
  OOOPS: 'Ooops! Something went wrong!',
  PLEASE_TRY_AGAIN: 'Please try using different keywords.',
};

export const MOCK_CHARACTERS_DATA: RickAndMortyCharacter[] = [
  {
    created: '2017-11-04T18:48:46.250Z',
    gender: 'Male',
    id: 1,
    location: 'Citadel of Ricks',
    name: 'Rick Sanchez',
    origin: 'Earth (C-137)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T18:50:21.651Z',
    gender: 'Male',
    id: 2,
    location: 'Citadel of Ricks',
    name: 'Morty Smith',
    origin: 'unknown',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:09:56.428Z',
    gender: 'Female',
    id: 3,
    location: 'Earth (Replacement Dimension)',
    name: 'Summer Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:22:43.665Z',
    gender: 'Female',
    id: 4,
    location: 'Earth (Replacement Dimension)',
    name: 'Beth Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:26:56.301Z',
    gender: 'Male',
    id: 5,
    location: 'Earth (Replacement Dimension)',
    name: 'Jerry Smith',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:50:28.250Z',
    gender: 'Female',
    id: 6,
    location: 'Abadango',
    name: 'Abadango Cluster Princess',
    origin: 'Abadango',
    species: 'Alien',
    status: 'Alive',
    type: '',
  },
  {
    created: '2017-11-04T19:59:20.523Z',
    gender: 'Male',
    id: 7,
    location: 'Testicle Monster Dimension',
    name: 'Abradolf Lincler',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'unknown',
    type: 'Genetic experiment',
  },
  {
    created: '2017-11-04T20:03:34.737Z',
    gender: 'Male',
    id: 8,
    location: 'Citadel of Ricks',
    name: 'Adjudicator Rick',
    origin: 'unknown',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:06:54.976Z',
    gender: 'Male',
    id: 9,
    location: 'Earth (Replacement Dimension)',
    name: 'Agency Director',
    origin: 'Earth (Replacement Dimension)',
    species: 'Human',
    status: 'Dead',
    type: '',
  },
  {
    created: '2017-11-04T20:19:09.017Z',
    gender: 'Male',
    id: 10,
    location: "Worldender's lair",
    name: 'Alan Rails',
    origin: 'unknown',
    species: 'Human',
    status: 'Dead',
    type: 'Superhuman (Ghost trains summoner)',
  },
];
